### ISSUE TITLE
[INV] Menu de Perfil e Frases Personalizadas

### ISSUE THREAD

**Issue by cfpgomes** [clavedefala/clavedefala_app#8]
**Problema em causa**
Existem várias frases e informações que são dependentes do utilizador. Por esta razão, a ausência de um menu de perfil (ou semelhante), não permite um tratamento personalizado para cada utilizador.

**Ideias-Chave**
1. Um utilizador pode dizer, com regularidade, certas informações, como o seu NIF, o número que calça, etc..
2. Para guardar estas informações, será necessário recorrer a um sistema de armazenamento, para que não se percam mesmo após a App ser encerrada.
3. Será que se pode interligar o sistema de armazenamento do perfil com o de frases personalizadas e, desta forma, simplificar a resolução dos dois problemas? (Ver #7)
4. Será necessário recorrer a tecnologias de armazenamento na nuvem?

**Comment by cfpgomes** [comment]
Em resposta às ideias-chave 2, 3 e 4:
Como estamos a tratar de uma coleção **pequena** de valores, o [plugin do shared_preferences](https://pub.dartlang.org/packages/shared_preferences), parece ser o mais adequado como sistema de armazenamento.
Este plugin usa as tecnologias NSUserDefaults (do iOS) e SharedPreferences (do Android), que guardam os dados numa estrutura baseada em pares chave-valores. Esta estrutura tem o potencial de facilitar o sistema das frases personalizadas, já que permite buscar os valores com recurso a uma chave.

**Comment by cfpgomes** [comment]
Em relação às frases personalizadas. Atualmente, a classe das frases contém uma simples string. Podemos implementar duas strings, que correspondem a duas partes da frase, e no meio colocaria-se o valor que obtém no sistema de armazenamento. Por exemplo, para a frase "Calço o número 42.", A primeira parte seria "Calço o número ", a segunda parte seria "." e, entre as duas partes, seria o valor devolvido quando buscávamos o valor associado à chave "Tamanho Calçado" no sistema de armazenamento, 42.
No entanto, este sistema não se adequa a frases com mais do que um valor pessoal. Será que existirão sugestões que requeiram 2 valores pessoais?

**Comment by antonioeloi** [comment]
Em resposta à questão de frases com 2 ou até mais valores pessoais penso que é sempre possível ao utilizador dividir uma frase em 2 frases, como por exemplo: "Pode ligar para o **Número de telemóvel #1**, se não atenderem para o **Número de telemóvel #2**" (sendo que esses números constavam no sistema de armazenamento) , em duas frases separadas.

**Comment by cfpgomes** [comment]
@aeloi98 Mas como é que ele faria a junção das duas frases separadas? Podes esclarecer nesse aspeto?

**Comment by antonioeloi** [comment]
@TofuLynx Claro! Não fazia a junção, simplesmente eram frases em separadas: "Pode ligar para o X1 por favor?" e depois "Pode ligar para o X2 por favor?".

**Comment by cfpgomes** [comment]
Pensei numa alternativa, que se calhar é muito mais flexível para nós. Em vez de complicações com novas variáveis para as várias partes das frases, a string, no exemplo acima, passaria simplesmente a ser "Calço o número {tamanhocalcado}.", que depois no toString passaria por um parser que identifica tudo o que está entre {}. Neste caso, o parser transformava "{tamanhocalcado}" em "42".
Este sistema seria mais versátil na medida em que continua tudo a ser uma só string, não necessitando de transformar a nossa base de dados de frases existente, já que só afeta a função toString() da classe Phrase. Ainda na versatilidade, também tem a vantagem de podermos colocar várias chavetas na string, suportando desta forma um número arbitrário de valores pessoais.
@aeloi98

**Comment by cfpgomes** [comment]
Ainda sobre o Parser acima, pode se usar esta [função](https://api.dartlang.org/stable/1.10.1/dart-core/String/allMatches.html) do Dart, com recurso a regex.
